version: "3.8"

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul-data:/consul/data
      - ./consul-config:/consul/config
    command: "agent -config-dir=/consul/config"

volumes:
  consul-data:
